### PR TITLE
Lrcraig lrcraig

### PR DESCRIPTION
**Pull request by lrcraig**
Replaced line 15, which was inadvertently removed.

### CODE REVIEW

**Comment by elwoodicious** [comment]
:+1: , merged it.

**Comment by elwoodicious** [comment]
I bungled the merge, tapping @tranqy to look it over and merge properly. :sweat_smile:

**Comment by tranqy** [comment]
lrcraig's changes are against the gh-pages branch, which is generated off the master branch. There are md files that we'll want to put these changes in instead.

I can try to fish them out, although git is seeing massive changes since I also made changes last week and the diff is on the generated files.  Lemme see what I can find.

**Comment by tranqy** [comment]
I don't see this branch published to github to clone, so I don't even know where this PR is coming from. Can lrcraig explicitly push the branch so I can diff locally?

**Comment by lrcraig** [comment]
Still learning GitHub. I will look and see if I can do this.

**Comment by lrcraig** [comment]
When I am comparing the branches in GitHub it shows that the Geezeo/master
branch has the index.html file pulled to it. Please advise.

Thanks!

**Comment by tranqy** [comment]
lrcraig, let's setup a call to figure out what to do here. We shouldn't be making changes directly to the index.html, that's a generated file. We should be changing the .md files which are then used to generate the html files. So either we need to fish the content out of the rendered index and migrate it (possibly hard), or if you have a good sense of what changed we might be better changing the md's directly. I'm traveling today, but around tomorrow/friday if you have time. Hit me at ajunod@geezeo.com .

**Pull request closed without merging**
